name: appstream
version: 0.2.4

description:
  A parser for Appstream data.
  This package allows Dart applications to access package metadata on Linux systems.

homepage: https://github.com/canonical/appstream.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

platforms:
  linux:

dependencies:
  xml: ^5.1.1
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
