name: appstream
version: 0.2.4

description:
  A parser for Appstream data.
  This package allows Dart applications to access package metadata on Linux systems.

homepage: https://github.com/canonical/appstream.dart

environment:
  sdk: '>=2.14.0 <3.0.0'

platforms:
  linux:

dependencies:
  xml: ^5.1.1
  yaml: ^3.1.0

# Appstream YAML is broken on Ubuntu - disable an assertion.
# https://github.com/ximion/appstream-generator/issues/92
dependency_overrides:
 yaml:
   git:
       url: git@github.com:robert-ancell/yaml.git
       ref: allow-duplicate-keys

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.8
